kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6445
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  - containerPort: 30844
    hostPort: 30844
  - containerPort: 31707
    hostPort: 31707
  extraMounts:
  - hostPath: HOSTPATH_PLACEHOLDER
    containerPath: /jenkins_home 