apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devops-pets
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # Using self-signed certificate instead of cert-manager
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jenkins.petsystem46.swedencentral.cloudapp.azure.com
    secretName: jenkins-tls
  rules:
  - host: jenkins.petsystem46.swedencentral.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080 