---
- name: Check if Java is installed
  shell: java -version
  register: java_check
  failed_when: false

- name: Install OpenJDK 17 if not present
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: yes
  when: java_check.rc != 0
  ignore_errors: yes

- name: Set JAVA_HOME if Java was installed
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
    state: present
  become: yes
  when: java_check.rc != 0
  ignore_errors: yes

- name: Display Java installation status
  debug:
    msg: |
      Java: {{ 'OK! Installed' if java_check.rc == 0 else 'Installation attempted' }} 